apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dealercenter-db
  description: dealercenter-db
spec:
  type: database
  owner: team dealercetner dba
  system: Nowcom Global Ecosystem
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: Nowcom Global Ecosystem
  description: Handy tools to keep artists in the loop
spec:
  owner: NowcomGlobal

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Team DealerCenter
  description: Team DealerCenter
spec:
  type: team
  profile:
    displayName: Team DealerCenter
    email: dealercenter-dev@nowcom.com
  children: [backstage, other]
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-app
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: DealerCenter-Website
  description: |
    DealerCenter Website
  links:
    - url: https://example.com/user
      title: public users
      icon: user
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://www.dealercenter.com
      title: Website
      icon: web
spec:
  type: webiste
  lifecycle: experimental
  owner: Team DealerCenter
  system: Nowcom Global Ecosystem
  dependsOn: ['resource:dealercenter-db']
  apiConsumedBy: ['component:www-dealercenter']
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: DealerCenter-API
  description: |
    DealerCenter API
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
    - url: https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.1/webhook-example.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: experimental
  owner: Team DealerCenter
  system: Nowcom Global Ecosystem
  providesApi:
    - DealerCenter-Website

