apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: DealerCenter-API
  description: |
    DealerCenter API
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
    - url: https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.1/webhook-example.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: experimental
  owner: Team DealerCenter
  system: Nowcom Global Ecosystem
  providesApi: ['component:DealerCenter-Website']
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: DealerCenter API
      license:
        name: MIT
    servers:
      - url: https://dealercenter.com
    paths:
      /cars:
        get:
          summary: List all cars